add_newline = true
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$docker_context\
$elixir\
$golang\
$lua\
$nodejs\
$php\
$python\
$ruby\
$cmd_duration\
$fill\
$os\
$shell\
$time\
$line_break\
$character"""

[character]
success_symbol = "[󰔶](bold white) "
error_symbol = "[](bold red) "

[fill]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "

[shell]
bash_indicator = "bash"
fish_indicator = "fish"
powershell_indicator = "powershell"
disabled = false
format = '\([$indicator]($style)\) '

[os]
disabled = false
format = '[$symbol]($style) ($version) '

[os.symbols]
Alpaquita = "Alpaquita"
Alpine = "Alpine"
Amazon = "Amazon"
Android = "Android"
Arch = "Arch"
Artix = "Artix"
CentOS = "CentOS"
Debian = "Debian"
DragonFly = "DragonFly"
Emscripten = "Emscripten"
EndeavourOS = "Endeavour OS"
Fedora = "Fedora" 
FreeBSD = "FreeBSD"
Garuda = "Garuda"
Gentoo = "Gentoo"
HardenedBSD = "HardenedBSD"
Illumos = "Illumos"
Linux = "Linux"
Mabox = "Mabox"
Macos = "Mac OS"
Manjaro = "Manjaro"
Mariner = "Mariner"
MidnightBSD = "MidnightBSD"
Mint = "Mint"
NetBSD = "NetBSD"
NixOS = "Nix OS"
OpenBSD = "OpenBSD"
OpenCloudOS = "OpenCloudOS"
openEuler = "openEuler"
openSUSE = "openSUSE"
OracleLinux = "OracleLinux"
Pop = "Pop"
Raspbian = "Raspbian"
Redhat = "Redhat"
RedHatEnterprise = "RedHat Enterprise"
Redox = "Redox"
Solus = "Solus"
SUSE = "SUSE"
Ubuntu = "Ubuntu"
Unknown = "Unknown"
Windows = "Windows"

[time]
disabled = false
