#!/usr/bin/env zsh

# ──────────────────────────────────────────────────────────────────────
# Script: Help
#
# This script will show the help message for the dotfiles executable.-
#
# ──────────────────────────────────────────────────────────────────────