#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh

#
# Helper Functions
# http://apple.stackexchange.com/a/96810/7647
#

update() {
    # Check if brew exists and add its update commands
    if command -v brew &>/dev/null; then
        echo ; gum style --bold '📦 UPDATING HOMEBREW'
        brew update && brew upgrade && brew cleanup || echo "Homebrew update failed"
    fi

    # Check if npm exists and add its update commands
    if command -v npm &>/dev/null; then
        lecho ; gum style --bold '📦 UPDATING NPM'
        npm update -g || echo "NPM global update failed"
    fi

    # Check if tldr exists and add its update commands
    if command -v tldr &>/dev/null; then
        echo ; gum style --bold '📦 UPDATING TLDR'
        tldr --update || echo "TLDR update failed"
    fi
}
